# Generated by Django 3.2.5 on 2022-06-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='session_id',
            field=models.CharField(max_length=32),
        ),
    ]
