# Generated by Django 3.2.5 on 2022-06-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_userprofile_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='session_id',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
