# Generated by Django 3.2.5 on 2022-06-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_userprofile_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='uid',
            field=models.CharField(default='', max_length=50),
        ),
    ]
