# Generated by Django 3.2.5 on 2022-06-28 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_userprofile_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='session_key',
        ),
    ]
